development:
  adapter: postgresql
  database: congress_development
  username: postgres
  password: 
  host: localhost

test:
  adapter: postgresql
  database: congress_test
  username: postgres
  password:
  host: localhost
  
production:
  adapter: postgresql
  database: congress_production
  username: deploy
  password:
  host: localhost